version: '3.7'

#volumes:
#  mlflow_backend:
#    driver: local

services:
  jupyter:
    container_name: ucla_jupyter
    hostname: ucla_jupyter
    build:
      context: docker-jupyter
    volumes:
      - /home/ubuntu/ucla-deeplearning:/app/git
    ports:
      - 7000:80
    command: [
      '/opt/conda/bin/jupyter',
      'lab',
      '--notebook-dir=/app',
      '--ip=0.0.0.0',
      '--port=80',
      '--no-browser',
      '--allow-root'
    ]

#  mlflow:
#    container_name: ucla_mlflow
#    hostname: ucla_mlflow
#    build:
#      context: docker-jupyter
#    ports:
#      - 7001:5000
#    volumes:
#      - mlflow_backend:/app/mlflow_backend
#    command: [
#      'mlflow',
#      'server',
#      '--backend-store-uri', 'sqlite:////app/mlflow_backend/sqlite.db',
#      '--default-artifact-root', '/app/mlflow_backend/artifacts',
#      '--host', '0.0.0.0'
#    ]
